### ISSUE TITLE
Visual Studio needed to build?

### ISSUE THREAD

**Issue by masbaehr** [cosmostation/web-wallet-ts-react#1]
Why is visual studio needed to build a web-app?

![image](https://user-images.githubusercontent.com/38694044/141489619-af334520-42b5-4f0f-a506-cba320ace310.png)

**Comment by ong-ar** [comment]
you don't need vscode to build this project.

only need nodejs v14, yarn (node package manager).
i don't know your error unfortunately.
maybe, the problem seems to be with the plugin you use.
